### ISSUE TITLE
pip install failing due to underscore on PyPI

### ISSUE THREAD

**Issue by avandendorpe** [WURFL/wurfl-cloud-client-python#2]
Hey, could you please republish this to PyPI with a dash rather than underscore to accommodate pip's idiosyncrasies? e.g. http://pybuilder.github.io/documentation/external_plugins.html 

Uploading tagged versions would be swell too :+1:

**Comment by elliotfehr** [comment]
Fixed in version 1.1.1

https://github.com/WURFL/wurfl-cloud-client-python/releases/tag/v1.1.1
